{"level":"error","service_name":"pgA","service_version":"","service_id":"78604854-2d49-42fc-96f0-3cb907010b36","timestamp":"2025-09-17T16:01:51.358119","message":"Table simf.credito_inmediato_enviado does not exist. Skipping data insertion."}
{"level":"error","service_name":"pgA","service_version":"","service_id":"dc4c9b47-8f5e-4a56-b8b9-0c6f676b26da","timestamp":"2025-09-17T16:07:57.96068","message":"Table simf.credito_inmediato_enviado does not exist. Skipping data insertion."}
{"level":"error","service_name":"pgA","service_version":"","service_id":"33391821-d9a5-4bd6-9573-81965004d31c","timestamp":"2025-09-17T16:07:57.961347","message":"Failed to run migration for table simf.credito_inmediato_enviado: table simf.credito_inmediato_enviado does not exist"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"d34a3aba-9016-463a-9003-2194f332fb5e","timestamp":"2025-09-17T16:24:13.636116","message":"Error starting Postgres container: generic container: create container: created hook: can't copy ./init.sql to container: open ./init.sql: no such file or directory with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"b64ab21f-c182-44ac-be90-dda8dda2f4ad","timestamp":"2025-09-17T16:25:01.331079","message":"Error starting Postgres container: generic container: create container: created hook: can't copy ./init.sql to container: open ./init.sql: no such file or directory with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"e277faf1-d7b9-42b8-b803-0c6d2863c6b1","timestamp":"2025-09-17T16:25:13.289087","message":"Error starting Postgres container: generic container: create container: created hook: can't copy ./init.sql to container: open ./init.sql: no such file or directory with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"27df2aa0-62c4-41a2-914b-240fb6cf6fbb","timestamp":"2025-09-17T16:29:03.622905","message":"Failed to create schema simf: failed to connect to `user=user database=postgres`:\n\t[::1]:49800 (localhost): tls error: EOF\n\t127.0.0.1:49800 (localhost): tls error: EOF\n\t[::1]:49800 (localhost): failed to receive message: unexpected EOF\n\t127.0.0.1:49800 (localhost): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"6eec6912-c113-4de4-b968-c9d1b63b3887","timestamp":"2025-09-17T16:29:03.623081","message":"Failed to run migration for table simf.credito_inmediato_enviado: failed to connect to `user=user database=postgres`:\n\t[::1]:49800 (localhost): tls error: EOF\n\t127.0.0.1:49800 (localhost): tls error: EOF\n\t[::1]:49800 (localhost): failed to receive message: unexpected EOF\n\t127.0.0.1:49800 (localhost): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"3c856530-33e6-4719-ad37-49288dbe0630","timestamp":"2025-09-17T16:30:01.33852","message":"Failed to create schema simf: failed to connect to `user=user database=postgres`:\n\t[::1]:49819 (localhost): tls error: EOF\n\t127.0.0.1:49819 (localhost): tls error: EOF\n\t[::1]:49819 (localhost): failed to receive message: unexpected EOF\n\t127.0.0.1:49819 (localhost): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"a547ac1b-f6fa-45b2-9165-62fe205aed67","timestamp":"2025-09-17T16:30:01.338679","message":"Failed to run migration for table simf.credito_inmediato_enviado: failed to connect to `user=user database=postgres`:\n\t[::1]:49819 (localhost): tls error: EOF\n\t127.0.0.1:49819 (localhost): tls error: EOF\n\t[::1]:49819 (localhost): failed to receive message: unexpected EOF\n\t127.0.0.1:49819 (localhost): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"599afbad-1e1e-412d-ac17-332830cdb80d","timestamp":"2025-09-17T16:30:30.393711","message":"Failed to create schema simf: failed to connect to `user=user database=postgres`:\n\t[::1]:49844 (localhost): tls error: EOF\n\t127.0.0.1:49844 (localhost): tls error: EOF\n\t[::1]:49844 (localhost): failed to receive message: unexpected EOF\n\t127.0.0.1:49844 (localhost): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"a074ec36-f28a-403a-a1f4-baf8e6bc6644","timestamp":"2025-09-17T16:30:30.393895","message":"Failed to run migration for table simf.credito_inmediato_enviado: failed to connect to `user=user database=postgres`:\n\t[::1]:49844 (localhost): tls error: EOF\n\t127.0.0.1:49844 (localhost): tls error: EOF\n\t[::1]:49844 (localhost): failed to receive message: unexpected EOF\n\t127.0.0.1:49844 (localhost): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"423b894a-7db6-4065-8e46-b3b9afc2e99f","timestamp":"2025-09-17T16:32:33.262616","message":"Failed to create schema simf: failed to connect to `user=user database=postgres`:\n\t[::1]:49870 (localhost): tls error: EOF\n\t127.0.0.1:49870 (localhost): tls error: EOF\n\t[::1]:49870 (localhost): failed to receive message: unexpected EOF\n\t127.0.0.1:49870 (localhost): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"9cc11384-7c44-4758-b112-0be031eaf0d8","timestamp":"2025-09-17T16:32:33.262798","message":"Failed to run migration for table simf.credito_inmediato_enviado: failed to connect to `user=user database=postgres`:\n\t[::1]:49870 (localhost): tls error: EOF\n\t127.0.0.1:49870 (localhost): tls error: EOF\n\t[::1]:49870 (localhost): failed to receive message: unexpected EOF\n\t127.0.0.1:49870 (localhost): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"68b1b39d-ee3a-4e7b-a690-4b91b0eb7730","timestamp":"2025-09-17T16:58:21.473429","message":"Failed to create schema simf: failed to connect to `user=user database=postgres`:\n\t[::1]:49917 (localhost): tls error: EOF\n\t127.0.0.1:49917 (localhost): tls error: EOF\n\t[::1]:49917 (localhost): failed to receive message: unexpected EOF\n\t127.0.0.1:49917 (localhost): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"411f465c-26f8-46a8-9f77-44c0659bdf95","timestamp":"2025-09-17T16:58:21.473597","message":"Failed to run migration for table simf.credito_inmediato_enviado: failed to connect to `user=user database=postgres`:\n\t[::1]:49917 (localhost): tls error: EOF\n\t127.0.0.1:49917 (localhost): tls error: EOF\n\t[::1]:49917 (localhost): failed to receive message: unexpected EOF\n\t127.0.0.1:49917 (localhost): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"d3e0eebc-14da-4529-8368-caf1b886fb51","timestamp":"2025-09-17T17:03:30.784292","message":"Failed to create schema simf: failed to connect to `user=user database=postgres`:\n\t[::1]:49968 (localhost): tls error: server refused TLS connection\n\t127.0.0.1:49968 (localhost): tls error: server refused TLS connection\n\t[::1]:49968 (localhost): server error: FATAL: terminating connection due to administrator command (SQLSTATE 57P01)\n\t127.0.0.1:49968 (localhost): server error: FATAL: the database system is shutting down (SQLSTATE 57P03)"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"325b1d98-5ef8-4b0d-8753-df8f479369cf","timestamp":"2025-09-17T17:03:30.784788","message":"Failed to run migration for table simf.credito_inmediato_enviado: failed to connect to `user=user database=postgres`:\n\t[::1]:49968 (localhost): tls error: server refused TLS connection\n\t127.0.0.1:49968 (localhost): tls error: server refused TLS connection\n\t[::1]:49968 (localhost): server error: FATAL: terminating connection due to administrator command (SQLSTATE 57P01)\n\t127.0.0.1:49968 (localhost): server error: FATAL: the database system is shutting down (SQLSTATE 57P03)"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"545e1a16-ca2d-4a26-9da8-0021b0048f64","timestamp":"2025-09-17T17:06:29.761577","message":"Failed to create schema simf: failed to connect to `user=user database=postgres`:\n\t0.0.21.56:5432 (5432): dial error: dial tcp 0.0.21.56:5432: connect: no route to host\n\t0.0.21.56:5432 (5432): dial error: dial tcp 0.0.21.56:5432: connect: no route to host"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"698f39ef-4cf4-4ce9-bb35-a42a7e626b35","timestamp":"2025-09-17T17:06:29.762082","message":"Failed to run migration for table simf.credito_inmediato_enviado: failed to connect to `user=user database=postgres`:\n\t0.0.21.56:5432 (5432): dial error: dial tcp 0.0.21.56:5432: connect: no route to host\n\t0.0.21.56:5432 (5432): dial error: dial tcp 0.0.21.56:5432: connect: no route to host"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"299501c7-b85a-4edc-8c63-2e58e915ef60","timestamp":"2025-09-17T17:07:11.127573","message":"Table simf.credito_inmediato_enviado does not exist. Skipping data insertion."}
{"level":"error","service_name":"pgA","service_version":"","service_id":"4064a955-a02d-4530-a1af-80f9f2de8715","timestamp":"2025-09-17T17:07:11.128216","message":"Failed to run migration for table simf.credito_inmediato_enviado: table simf.credito_inmediato_enviado does not exist"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"4b82af73-778b-43b6-850a-2245dda15fdc","timestamp":"2025-09-17T17:07:49.30878","message":"Failed to create schema simf: failed to connect to `user=user database=postgres`: 127.0.0.1:5432 (127.0.0.1): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"c4963306-2802-4291-92f3-a8f168b9cf68","timestamp":"2025-09-17T17:07:49.308953","message":"Failed to run migration for table simf.credito_inmediato_enviado: failed to connect to `user=user database=postgres`: 127.0.0.1:5432 (127.0.0.1): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"619a2210-8b98-43e5-8b96-d1f833bb1069","timestamp":"2025-09-17T17:09:33.822279","message":"Failed to create schema simf: failed to connect to `user=user database=postgres`: 127.0.0.1:5432 (127.0.0.1): failed SASL auth: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"57ab77e3-79f8-4a7d-b5a6-44b4e65b5042","timestamp":"2025-09-17T17:09:33.822973","message":"Failed to run migration for table simf.credito_inmediato_enviado: failed to connect to `user=user database=postgres`: 127.0.0.1:5432 (127.0.0.1): failed SASL auth: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"442bd117-4759-434e-ab5e-d8f1e0e5a033","timestamp":"2025-09-18T12:05:52.431605","message":"Failed to create schema simf: failed to connect to `user=user database=postgres`: 127.0.0.1:5432 (127.0.0.1): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"143f35fa-e32a-4ac0-9750-847d8ba24801","timestamp":"2025-09-18T12:05:52.431954","message":"Failed to run migration for table simf.credito_inmediato_enviado: failed to connect to `user=user database=postgres`: 127.0.0.1:5432 (127.0.0.1): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"f9cfb114-300e-4790-9f53-9e5f402061a3","timestamp":"2025-09-22T11:14:06.184353","message":"Recover from Panic check host \"unix:///var/run/docker.sock\": docker info: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\ncheck host \"unix:///Users/quintero/.docker/run/docker.sock\": docker info: Cannot connect to the Docker daemon at unix:///Users/quintero/.docker/run/docker.sock. Is the docker daemon running? , server with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"078deb9b-dcca-4fe8-a760-b14511297ced","timestamp":"2025-09-22T11:18:21.897135","message":"Recover from Panic check host \"unix:///var/run/docker.sock\": docker info: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\ncheck host \"unix:///Users/quintero/.docker/run/docker.sock\": docker info: Cannot connect to the Docker daemon at unix:///Users/quintero/.docker/run/docker.sock. Is the docker daemon running? , server with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"bbe24b60-83b6-4199-a161-51ad2dddf1c4","timestamp":"2025-09-22T11:25:05.153471","message":"Recover from Panic check host \"unix:///var/run/docker.sock\": docker info: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\ncheck host \"unix:///Users/quintero/.docker/run/docker.sock\": docker info: Cannot connect to the Docker daemon at unix:///Users/quintero/.docker/run/docker.sock. Is the docker daemon running? , server with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"0721e712-1468-4fa7-b0af-87d38a386e5d","timestamp":"2025-09-22T15:59:08.545815","message":"Recover from Panic check host \"unix:///var/run/docker.sock\": docker info: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\ncheck host \"unix:///Users/quintero/.docker/run/docker.sock\": docker info: Cannot connect to the Docker daemon at unix:///Users/quintero/.docker/run/docker.sock. Is the docker daemon running? , server with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"e9c182da-3de7-4eff-b188-a0279b0bee31","timestamp":"2025-09-22T15:59:49.397845","message":"Recover from Panic check host \"unix:///var/run/docker.sock\": docker info: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\ncheck host \"unix:///Users/quintero/.docker/run/docker.sock\": docker info: Cannot connect to the Docker daemon at unix:///Users/quintero/.docker/run/docker.sock. Is the docker daemon running? , server with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"ddc53632-2c9b-4e54-870b-7447c51e8aef","timestamp":"2025-09-22T16:08:03.100396","message":"Recover from Panic check host \"unix:///var/run/docker.sock\": docker info: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\ncheck host \"unix:///Users/quintero/.docker/run/docker.sock\": docker info: Cannot connect to the Docker daemon at unix:///Users/quintero/.docker/run/docker.sock. Is the docker daemon running? , server with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"ddc53632-2c9b-4e54-870b-7447c51e8aef","timestamp":"2025-09-22T16:08:05.478973","message":"Panic recover. Error stopping Postgres container: runtime error: invalid memory address or nil pointer dereference with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"18fce38d-93f7-4d8c-8700-797b5a13b807","timestamp":"2025-09-23T09:13:06.193835","message":"Recover from Panic <nil> , server with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"431a0683-77f2-4834-9059-cecf7ec43b16","timestamp":"2025-09-23T09:13:06.198823","message":"Failed to create schema simf: failed to connect to `user=user database=postgres`: 127.0.0.1:5432 (127.0.0.1): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"18fce38d-93f7-4d8c-8700-797b5a13b807","timestamp":"2025-09-23T09:13:06.198927","message":"Failed to run migration for table simf.credito_inmediato_enviado: failed to connect to `user=user database=postgres`: 127.0.0.1:5432 (127.0.0.1): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"b1b25026-6107-4f0b-bff3-61ba018cfd83","timestamp":"2025-09-23T09:19:06.939708","message":"Recover from Panic <nil> , server with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"1496709d-86e4-409f-9eb5-48aaead68d66","timestamp":"2025-09-23T09:19:06.943429","message":"Failed to create schema simf: failed to connect to `user=user database=postgres`: 127.0.0.1:5432 (127.0.0.1): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"b1b25026-6107-4f0b-bff3-61ba018cfd83","timestamp":"2025-09-23T09:19:06.943508","message":"Failed to run migration for table simf.credito_inmediato_enviado: failed to connect to `user=user database=postgres`: 127.0.0.1:5432 (127.0.0.1): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"47226ada-450f-4f9c-a79f-8fec40912a05","timestamp":"2025-09-23T09:23:36.71556","message":"Recover from Panic <nil> , server with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"37ed3a45-add9-41da-806f-c848c248e37e","timestamp":"2025-09-23T09:23:36.720188","message":"Failed to create schema simf: failed to connect to `user=user database=postgres`: 127.0.0.1:5432 (127.0.0.1): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"47226ada-450f-4f9c-a79f-8fec40912a05","timestamp":"2025-09-23T09:23:36.720275","message":"Failed to run migration for table simf.credito_inmediato_enviado: failed to connect to `user=user database=postgres`: 127.0.0.1:5432 (127.0.0.1): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"03d411a6-6d89-4011-b616-8ea71b4b2dea","timestamp":"2025-09-23T13:30:11.689942","message":"Recover from Panic <nil> , server with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"ccc9212c-8ea4-4e26-bdb3-9573468ad38a","timestamp":"2025-09-23T13:30:11.69484","message":"Failed to create schema simf: failed to connect to `user=user database=postgres`: 127.0.0.1:5432 (127.0.0.1): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"03d411a6-6d89-4011-b616-8ea71b4b2dea","timestamp":"2025-09-23T13:30:11.694941","message":"Failed to run migration for table simf.credito_inmediato_enviado: failed to connect to `user=user database=postgres`: 127.0.0.1:5432 (127.0.0.1): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"9284a54d-4e72-4e2b-8c3b-6127d3aa3a06","timestamp":"2025-09-23T13:31:10.027365","message":"Recover from Panic <nil> , server with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"6351584e-d9f0-439b-baf6-5cb2736ca82f","timestamp":"2025-09-23T13:31:10.029935","message":"Failed to create schema simf: failed to connect to `user=user database=postgres`: 127.0.0.1:5432 (127.0.0.1): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"9284a54d-4e72-4e2b-8c3b-6127d3aa3a06","timestamp":"2025-09-23T13:31:10.029982","message":"Failed to run migration for table simf.credito_inmediato_enviado: failed to connect to `user=user database=postgres`: 127.0.0.1:5432 (127.0.0.1): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"c6e66ec0-da5b-425d-a62e-f5e617305a90","timestamp":"2025-09-23T13:31:24.24029","message":"Recover from Panic <nil> , server with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"8fb595be-d042-45e3-8cbf-a8d2699a8614","timestamp":"2025-09-23T13:31:24.243348","message":"Failed to create schema simf: failed to connect to `user=user database=postgres`: 127.0.0.1:5432 (127.0.0.1): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"c6e66ec0-da5b-425d-a62e-f5e617305a90","timestamp":"2025-09-23T13:31:24.243435","message":"Failed to run migration for table simf.credito_inmediato_enviado: failed to connect to `user=user database=postgres`: 127.0.0.1:5432 (127.0.0.1): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"4650ce5b-11c8-463a-ad14-52617b507c3b","timestamp":"2025-09-23T13:41:13.578568","message":"Recover from Panic <nil> , server with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"bf42ba1b-aa02-4405-85b6-4001f3bfb4e7","timestamp":"2025-09-23T13:41:13.58225","message":"Failed to create schema simf: failed to connect to `user=user database=postgres`: 127.0.0.1:5432 (127.0.0.1): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"4650ce5b-11c8-463a-ad14-52617b507c3b","timestamp":"2025-09-23T13:41:13.582325","message":"Failed to run migration for table simf.credito_inmediato_enviado: failed to connect to `user=user database=postgres`: 127.0.0.1:5432 (127.0.0.1): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"0b11a1f7-18a9-4f79-b926-036f674323d8","timestamp":"2025-09-23T13:46:44.121879","message":"Recover from Panic <nil> , server with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"b1540289-1654-4961-a540-84d43cde3962","timestamp":"2025-09-23T13:46:44.125492","message":"Failed to create schema simf: failed to connect to `user=user database=postgres`: 127.0.0.1:5432 (127.0.0.1): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"0b11a1f7-18a9-4f79-b926-036f674323d8","timestamp":"2025-09-23T13:46:44.125601","message":"Failed to run migration for table simf.credito_inmediato_enviado: failed to connect to `user=user database=postgres`: 127.0.0.1:5432 (127.0.0.1): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"1ba988c8-c393-418f-aba0-bcf57d4ab60a","timestamp":"2025-09-23T13:47:18.48889","message":"Recover from Panic <nil> , server with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"77518fd5-de68-4f88-9a5b-f6034343f9d7","timestamp":"2025-09-23T13:47:18.493767","message":"Failed to create schema simf: failed to connect to `user=user database=postgres`: 127.0.0.1:5432 (127.0.0.1): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"1ba988c8-c393-418f-aba0-bcf57d4ab60a","timestamp":"2025-09-23T13:47:18.493877","message":"Failed to run migration for table simf.credito_inmediato_enviado: failed to connect to `user=user database=postgres`: 127.0.0.1:5432 (127.0.0.1): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"76e0f0d1-9bb7-4310-bdf6-299e94f49475","timestamp":"2025-09-23T13:49:48.143809","message":"Recover from Panic <nil> , server with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"383e39cc-b2d1-486a-9269-bc79bd98e031","timestamp":"2025-09-23T13:49:48.146203","message":"Failed to create schema simf: failed to connect to `user=user database=postgres`: 127.0.0.1:5432 (127.0.0.1): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"76e0f0d1-9bb7-4310-bdf6-299e94f49475","timestamp":"2025-09-23T13:49:48.146237","message":"Failed to run migration for table simf.credito_inmediato_enviado: failed to connect to `user=user database=postgres`: 127.0.0.1:5432 (127.0.0.1): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"4d4b98b5-05d2-4c88-bbd7-4b4f98134dcb","timestamp":"2025-09-23T13:51:25.854494","message":"Recover from Panic <nil> , server with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"fff96234-bc6b-427a-9af0-06c689c5ffc6","timestamp":"2025-09-23T13:51:25.858978","message":"Failed to create schema simf: failed to connect to `user=user database=postgres`: 127.0.0.1:5432 (127.0.0.1): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"4d4b98b5-05d2-4c88-bbd7-4b4f98134dcb","timestamp":"2025-09-23T13:51:25.859069","message":"Failed to run migration for table simf.credito_inmediato_enviado: failed to connect to `user=user database=postgres`: 127.0.0.1:5432 (127.0.0.1): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"3396e34b-2926-45d9-adcf-ed5848f7849b","timestamp":"2025-09-23T13:53:37.264854","message":"Recover from Panic <nil> , server with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"0a111fbe-bdfa-4db9-96d0-34494b11c602","timestamp":"2025-09-23T13:53:37.26879","message":"Failed to create schema simf: failed to connect to `user=user database=postgres`: 127.0.0.1:5432 (127.0.0.1): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"3396e34b-2926-45d9-adcf-ed5848f7849b","timestamp":"2025-09-23T13:53:37.268893","message":"Failed to run migration for table simf.credito_inmediato_enviado: failed to connect to `user=user database=postgres`: 127.0.0.1:5432 (127.0.0.1): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"0fae5c8b-d69b-498e-9425-884b4dadac91","timestamp":"2025-09-23T16:57:20.793119","message":"Recover from Panic <nil> , server with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"1b552bbf-29b6-44e7-a805-6e08f654f6d0","timestamp":"2025-09-23T16:57:20.800063","message":"Failed to create schema simf: failed to connect to `user=user database=postgres`: 127.0.0.1:5432 (127.0.0.1): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"0fae5c8b-d69b-498e-9425-884b4dadac91","timestamp":"2025-09-23T16:57:20.800144","message":"Failed to run migration for table simf.credito_inmediato_enviado: failed to connect to `user=user database=postgres`: 127.0.0.1:5432 (127.0.0.1): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"b748e8fe-906b-4728-a698-ede7141c6119","timestamp":"2025-09-23T16:58:05.78034","message":"Recover from Panic <nil> , server with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"3394b872-cf1f-4229-a58d-87a2369adc6d","timestamp":"2025-09-23T16:58:05.782948","message":"Failed to create schema simf: failed to connect to `user=user database=postgres`: 127.0.0.1:5432 (127.0.0.1): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"b748e8fe-906b-4728-a698-ede7141c6119","timestamp":"2025-09-23T16:58:05.782987","message":"Failed to run migration for table simf.credito_inmediato_enviado: failed to connect to `user=user database=postgres`: 127.0.0.1:5432 (127.0.0.1): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"ccb9cfd8-24ee-4e87-b709-0db055539a9a","timestamp":"2025-09-24T16:32:07.326829","message":"Recover from Panic check host \"unix:///var/run/docker.sock\": docker info: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\ncheck host \"unix:///Users/quintero/.docker/run/docker.sock\": docker info: Cannot connect to the Docker daemon at unix:///Users/quintero/.docker/run/docker.sock. Is the docker daemon running? , server with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"ccb9cfd8-24ee-4e87-b709-0db055539a9a","timestamp":"2025-09-24T16:32:17.988101","message":"Panic recover. Error stopping Postgres container: runtime error: invalid memory address or nil pointer dereference with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"afef2d5c-cdca-44b0-8ab4-47bb5af1016e","timestamp":"2025-09-25T14:55:33.339561","message":"Recover from Panic check host \"unix:///var/run/docker.sock\": docker info: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\ncheck host \"unix:///Users/quintero/.docker/run/docker.sock\": docker info: Cannot connect to the Docker daemon at unix:///Users/quintero/.docker/run/docker.sock. Is the docker daemon running? , server with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"afef2d5c-cdca-44b0-8ab4-47bb5af1016e","timestamp":"2025-09-25T14:57:09.837988","message":"Panic recover. Error stopping Postgres container: runtime error: invalid memory address or nil pointer dereference with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"b9484dcc-c87f-44a5-9ffa-bd8bf2e4b544","timestamp":"2025-09-25T14:57:19.628304","message":"Recover from Panic check host \"unix:///var/run/docker.sock\": docker info: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\ncheck host \"unix:///Users/quintero/.docker/run/docker.sock\": docker info: Cannot connect to the Docker daemon at unix:///Users/quintero/.docker/run/docker.sock. Is the docker daemon running? , server with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"b9484dcc-c87f-44a5-9ffa-bd8bf2e4b544","timestamp":"2025-09-25T14:59:58.720131","message":"Panic recover. Error stopping Postgres container: runtime error: invalid memory address or nil pointer dereference with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"f330144f-60ab-4df2-ba77-5ceed90c51b2","timestamp":"2025-09-25T15:00:02.528085","message":"Recover from Panic check host \"unix:///var/run/docker.sock\": docker info: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\ncheck host \"unix:///Users/quintero/.docker/run/docker.sock\": docker info: Cannot connect to the Docker daemon at unix:///Users/quintero/.docker/run/docker.sock. Is the docker daemon running? , server with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"f330144f-60ab-4df2-ba77-5ceed90c51b2","timestamp":"2025-09-25T15:01:16.739104","message":"Panic recover. Error stopping Postgres container: runtime error: invalid memory address or nil pointer dereference with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"f14ad174-989c-44f1-a907-99d8b2bbec31","timestamp":"2025-09-25T15:01:17.675423","message":"Recover from Panic check host \"unix:///var/run/docker.sock\": docker info: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\ncheck host \"unix:///Users/quintero/.docker/run/docker.sock\": docker info: Cannot connect to the Docker daemon at unix:///Users/quintero/.docker/run/docker.sock. Is the docker daemon running? , server with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"f14ad174-989c-44f1-a907-99d8b2bbec31","timestamp":"2025-09-25T15:01:29.865504","message":"Panic recover. Error stopping Postgres container: runtime error: invalid memory address or nil pointer dereference with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"3b9a8f1b-41d2-437b-a1f4-e8841fe6e9ef","timestamp":"2025-09-25T15:01:30.716442","message":"Recover from Panic check host \"unix:///var/run/docker.sock\": docker info: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\ncheck host \"unix:///Users/quintero/.docker/run/docker.sock\": docker info: Cannot connect to the Docker daemon at unix:///Users/quintero/.docker/run/docker.sock. Is the docker daemon running? , server with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"3b9a8f1b-41d2-437b-a1f4-e8841fe6e9ef","timestamp":"2025-09-25T15:01:41.004061","message":"Panic recover. Error stopping Postgres container: runtime error: invalid memory address or nil pointer dereference with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"50d431e3-1429-4449-8154-43a67df1ae5e","timestamp":"2025-09-25T15:01:41.811631","message":"Recover from Panic check host \"unix:///var/run/docker.sock\": docker info: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\ncheck host \"unix:///Users/quintero/.docker/run/docker.sock\": docker info: Cannot connect to the Docker daemon at unix:///Users/quintero/.docker/run/docker.sock. Is the docker daemon running? , server with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"50d431e3-1429-4449-8154-43a67df1ae5e","timestamp":"2025-09-25T15:02:04.264514","message":"Panic recover. Error stopping Postgres container: runtime error: invalid memory address or nil pointer dereference with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"42c9cf16-47ca-4232-924d-cacec7c36fb8","timestamp":"2025-09-25T15:02:05.15532","message":"Recover from Panic check host \"unix:///var/run/docker.sock\": docker info: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\ncheck host \"unix:///Users/quintero/.docker/run/docker.sock\": docker info: Cannot connect to the Docker daemon at unix:///Users/quintero/.docker/run/docker.sock. Is the docker daemon running? , server with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"42c9cf16-47ca-4232-924d-cacec7c36fb8","timestamp":"2025-09-25T15:02:52.114371","message":"Panic recover. Error stopping Postgres container: runtime error: invalid memory address or nil pointer dereference with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"9b94ec54-8a98-4639-ad31-ccd57b464ac7","timestamp":"2025-09-25T15:02:57.884711","message":"Recover from Panic check host \"unix:///var/run/docker.sock\": docker info: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\ncheck host \"unix:///Users/quintero/.docker/run/docker.sock\": docker info: Cannot connect to the Docker daemon at unix:///Users/quintero/.docker/run/docker.sock. Is the docker daemon running? , server with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"9b94ec54-8a98-4639-ad31-ccd57b464ac7","timestamp":"2025-09-25T15:06:09.064807","message":"Panic recover. Error stopping Postgres container: runtime error: invalid memory address or nil pointer dereference with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"99d87c76-e572-488d-84a3-192084a6ec64","timestamp":"2025-09-25T15:09:15.907242","message":"Recover from Panic check host \"unix:///var/run/docker.sock\": docker info: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\ncheck host \"unix:///Users/quintero/.docker/run/docker.sock\": docker info: Cannot connect to the Docker daemon at unix:///Users/quintero/.docker/run/docker.sock. Is the docker daemon running? , server with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"99d87c76-e572-488d-84a3-192084a6ec64","timestamp":"2025-09-25T15:09:48.464818","message":"Panic recover. Error stopping Postgres container: runtime error: invalid memory address or nil pointer dereference with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"00cbb962-5cee-4097-9a48-418eac3a965a","timestamp":"2025-09-25T15:12:44.180043","message":"Recover from Panic check host \"unix:///var/run/docker.sock\": docker info: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\ncheck host \"unix:///Users/quintero/.docker/run/docker.sock\": docker info: Cannot connect to the Docker daemon at unix:///Users/quintero/.docker/run/docker.sock. Is the docker daemon running? , server with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"00cbb962-5cee-4097-9a48-418eac3a965a","timestamp":"2025-09-25T15:14:20.976004","message":"Panic recover. Error stopping Postgres container: runtime error: invalid memory address or nil pointer dereference with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"0e6766d2-c78c-4766-b973-df95d01ac7c6","timestamp":"2025-09-25T15:14:21.925652","message":"Recover from Panic check host \"unix:///var/run/docker.sock\": docker info: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\ncheck host \"unix:///Users/quintero/.docker/run/docker.sock\": docker info: Cannot connect to the Docker daemon at unix:///Users/quintero/.docker/run/docker.sock. Is the docker daemon running? , server with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"0e6766d2-c78c-4766-b973-df95d01ac7c6","timestamp":"2025-09-25T15:25:53.74985","message":"Panic recover. Error stopping Postgres container: runtime error: invalid memory address or nil pointer dereference with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"856b8a02-2968-4877-81d9-89c764ff9159","timestamp":"2025-09-25T15:25:55.856854","message":"Recover from Panic <nil> , server with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"d7792ece-90f5-45de-8f7e-a175085894f0","timestamp":"2025-09-25T15:26:00.49003","message":"Table simf.credito_inmediato_enviado does not exist. Skipping data insertion."}
{"level":"error","service_name":"pgA","service_version":"","service_id":"856b8a02-2968-4877-81d9-89c764ff9159","timestamp":"2025-09-25T15:26:00.490397","message":"Failed to run migration for table simf.credito_inmediato_enviado: table simf.credito_inmediato_enviado does not exist"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"07621cd9-b8b8-4e72-be70-611a8fbbfe27","timestamp":"2025-09-25T15:27:04.027844","message":"Recover from Panic <nil> , server with Name: pgA"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"a210f386-2d77-471b-b128-daf29ac90d82","timestamp":"2025-09-25T15:27:04.033918","message":"Failed to create schema simf: failed to connect to `user=user database=postgres`: 127.0.0.1:5432 (127.0.0.1): failed to receive message: unexpected EOF"}
{"level":"error","service_name":"pgA","service_version":"","service_id":"07621cd9-b8b8-4e72-be70-611a8fbbfe27","timestamp":"2025-09-25T15:27:04.034061","message":"Failed to run migration for table simf.credito_inmediato_enviado: failed to connect to `user=user database=postgres`: 127.0.0.1:5432 (127.0.0.1): failed to receive message: unexpected EOF"}
